from setuptools import find_packages, setup

setup(
    name="pyvcell",
    version="0.1.1",
    description="This is the python wrapper for vcell modeling and simulation",
    author="Jim Schaff",
    author_email="fschaff@uchc.edu",
    url="https://github.com/virtualcell/pyvcell",
    project_urls={
        "Documentation": "https://virtualcell.github.io/pyvcell/",
        "Source": "https://github.com/virtualcell/pyvcell",
    },
    packages=find_packages(include=["pyvcell", "pyvcell.*", "tests"]),
    python_requires=">=3.10,<4.0",
    install_requires=[
        "numexpr>=2.10.0",
        "zarr>=2.17.2",
        "h5py>=3.11.0",
        "numpy>=1.26.4",
        "orjson>=3.10.3",
        "vtk>=9.3.1",
        "pyvcell-fvsolver>=0.1.0",
        "typer>=0.12.3",
        "pydantic>=2.10.5",
        "requests-oauth2client>=1.6.0",
        "overrides>=7.7.0",
        "typing-extensions>=4.12.2",
        "urllib3>=2.3.0",
        "requests>=2.32.3",
        "python-dateutil>=2.9.0.post0",
        "pyvista>=0.44.2",
        "python-libsbml>=5.20.4",
        "matplotlib>=3.10.0",
    ],
    extras_require={
        "bootstrap": ["setuptools", "ipython"],
        "dev": [
            "pytest>=7.2.0",
            "pytest-cov>=4.0.0",
            "deptry>=0.16.2",
            "mypy>=1.5.1",
            "pre-commit>=3.8.0",
            "tox>=4.11.1",
            "types-requests>=2.32.0.20241016",
            "notebook>=7.3.2",
        ],
        "docs": [
            "mkdocs>=1.6.1",
            "mkdocs-material>=9.5.50",
            "mkdocstrings[python]>=0.27.0",
            "griffe>=1.5.5",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
    ],
)
