"""
VCell API

VCell API

The version of the OpenAPI document: 1.0.1
Contact: vcell_support@uchc.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from pyvcell.api.vcell_client.models.field_data_reference import FieldDataReference


class TestFieldDataReference(unittest.TestCase):
    """FieldDataReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldDataReference:
        """Test FieldDataReference
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FieldDataReference`
        """
        model = FieldDataReference()
        if include_optional:
            return FieldDataReference(
                external_data_identifier = pyvcell.api.vcell_client.models.external_data_identifier.ExternalDataIdentifier(
                    key = pyvcell.api.vcell_client.models.key_value.KeyValue(
                        value = 1.337, ),
                    owner = pyvcell.api.vcell_client.models.user.User(
                        user_name = '',
                        name = '',
                        test_account = True, ),
                    name = '',
                    job_index = 56,
                    simulation_key = pyvcell.api.vcell_client.models.key_value.KeyValue(
                        value = 1.337, ),
                    parameter_scan_type = True,
                    data_key = , ),
                external_data_annotation = '',
                external_data_id_sim_refs = [
                    pyvcell.api.vcell_client.models.key_value.KeyValue(
                        value = 1.337, )
                    ]
            )
        else:
            return FieldDataReference(
        )
        """

    def testFieldDataReference(self):
        """Test FieldDataReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
