name: "setup-uv-env"
description: "Composite action to setup the Python and uv environment."

inputs:
  python-version:
    required: true
    description: "The python version to use"

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash

    - name: Install dependencies
      run: |
        uv venv --python $(python${{ inputs.python-version }} --version | awk '{print $2;}')
        uv sync --all-groups
      shell: bash
