"""Author and run a moving-boundary simulation.

The moving-boundary path differs from the finite-volume path in two ways: the
solver math (a moving membrane front with a prescribed velocity) is generated by
libvcell from application-level ``SpatialObjects``/``SpatialProcesses``, and the
result lives on a moving mesh rather than a fixed Cartesian grid.

:func:`simulate_moving_boundary` drives the full pipeline:

1. write the biomodel to VCML and round-trip through libvcell
   (:func:`~pyvcell.vcml.utils.to_vcml_str`), which makes VCell compute the
   geometry regions and auto-generate the canonical ``SpatialObjects``;
2. enable the surface's ``SurfaceVelocity`` quantity and inject a
   ``SurfaceKinematics`` process carrying the front velocity declared by
   :meth:`~pyvcell.vcml.models_app.Application.set_moving_boundary_front`;
3. round-trip again so libvcell generates the moving-boundary math
   (a ``MembraneSubDomain`` with a velocity);
4. convert to a ``MovingBoundarySetup`` XML and run ``pyvcell_mbsolver``.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from lxml import etree
from lxml.etree import Element, _Element

from pyvcell.sim_results.moving_boundary_result import MovingBoundaryResult
from pyvcell.vcml.models import Application, Biomodel, FrontVelocity, Simulation
from pyvcell.vcml.utils import to_vcml_str
from pyvcell.vcml.workspace import get_workspace_dir

_VCML_NS = "http://sourceforge.net/projects/vcell/vcml"


def _q(tag: str) -> str:
    return f"{{{_VCML_NS}}}{tag}"


def simulate_moving_boundary(biomodel: Biomodel, simulation: Simulation | str) -> MovingBoundaryResult:
    """Run a moving-boundary simulation and return its moving-mesh trajectory.

    The named simulation must be configured for the Moving Boundary solver (see
    :meth:`~pyvcell.vcml.models_app.Application.add_moving_boundary_sim`) and its
    application must declare a moving front via
    :meth:`~pyvcell.vcml.models_app.Application.set_moving_boundary_front`.

    Requires the ``native`` (libvcell >= 0.0.16) and ``mb`` (pyvcell-mbsolver)
    extras.
    """
    # Validate the model up front (cheap, no optional deps) so misconfiguration
    # raises a clear error even when the solver extras are not installed.
    simulation_name = simulation if isinstance(simulation, str) else simulation.name
    application, sim = _find_simulation(biomodel, simulation_name)
    if not sim.is_moving_boundary:
        raise ValueError(
            f"simulation '{simulation_name}' is not configured for the Moving Boundary solver "
            f"(solver={sim.solver!r}); use Application.add_moving_boundary_sim(...)"
        )
    if application.front_velocity is None:
        raise ValueError(
            f"application '{application.name}' has no moving front; "
            f"call Application.set_moving_boundary_front(...) before simulating"
        )

    import libvcell

    try:
        from pyvcell._internal.solvers.mbsolver import solve_moving_boundary
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "pyvcell.vcml.simulate_moving_boundary requires the optional dependency 'pyvcell-mbsolver', "
            "which is not installed. Install it with `pip install pyvcell[mb]`."
        ) from exc

    # Step 1: round-trip so VCell computes regions and auto-generates SpatialObjects.
    refined_vcml = to_vcml_str(biomodel)

    # Step 2: enable SurfaceVelocity and inject the SurfaceKinematics front velocity.
    kinematics_vcml = _inject_front_kinematics(refined_vcml, application.name, application.front_velocity)

    out_dir = Path(tempfile.mkdtemp(prefix="mb_out_dir_", dir=get_workspace_dir()))

    # Step 3: round-trip again so libvcell generates the moving-boundary math.
    refined_path = out_dir / "refined_mb.vcml"
    success, message = libvcell.vcml_to_vcml(vcml_content=kinematics_vcml, vcml_file_path=refined_path)
    if not success:
        raise ValueError(f"Failed to generate moving-boundary math: {message}")

    # Step 4: convert to a MovingBoundarySetup XML.
    success, message = libvcell.vcml_to_moving_boundary_input(
        vcml_content=refined_path.read_text(), simulation_name=simulation_name, output_dir_path=out_dir
    )
    if not success:
        raise ValueError(f"Failed to generate moving-boundary solver input: {message}")

    setup_file = next((out_dir / f for f in os.listdir(out_dir) if f.endswith("mb.xml")), None)
    if setup_file is None or setup_file.stat().st_size == 0:
        raise ValueError("MovingBoundarySetup XML not found")

    species_names = _species_order(setup_file)
    output_times = _output_times(sim)
    return solve_moving_boundary(setup_file, species_names=species_names, output_times=output_times)


def _find_simulation(biomodel: Biomodel, simulation_name: str) -> tuple[Application, Simulation]:
    for application in biomodel.applications:
        for sim in application.simulations:
            if sim.name == simulation_name:
                return application, sim
    raise ValueError(f"simulation '{simulation_name}' not found in biomodel '{biomodel.name}'")


def _inject_front_kinematics(vcml: str, application_name: str, front: FrontVelocity) -> str:
    """Enable SurfaceVelocity on the front surface and add its SurfaceKinematics process."""
    root = etree.fromstring(vcml.encode())
    spec = next(
        (s for s in root.iter(_q("SimulationSpec")) if s.get("Name") == application_name),
        None,
    )
    if spec is None:
        raise ValueError(f"application '{application_name}' not found in regenerated VCML")

    surface_object = _select_surface_object(spec, front.surface_name)
    surface_name = surface_object.get("Name")
    if surface_name is None:
        raise ValueError("regenerated surface object has no Name")
    for category in surface_object.iter(_q("QuantityCategory")):
        if category.get("Name") == "SurfaceVelocity":
            category.set("Enabled", "true")

    processes = spec.find(_q("SpatialProcesses"))
    if processes is None:
        processes = Element("SpatialProcesses")
        spec.append(processes)
    process = Element("SpatialProcess", Name="sproc_0", Type="SurfaceKinematics", SurfaceObject=surface_name)
    processes.append(process)
    for parameter_name, role, value in (
        ("velocityX", "SurfaceVelocityX", front.velocity_x),
        ("velocityY", "SurfaceVelocityY", front.velocity_y),
        ("velocityZ", "SurfaceVelocityZ", front.velocity_z),
    ):
        parameter = Element("Parameter", Name=parameter_name, Role=role, Unit="um.s-1")
        parameter.text = str(value)
        process.append(parameter)
    return etree.tostring(root).decode()


def _select_surface_object(spec: _Element, surface_name: str | None) -> _Element:
    surface_objects = [obj for obj in spec.iter(_q("SpatialObject")) if obj.get("Type") == "Surface"]
    if not surface_objects:
        raise ValueError("regenerated geometry has no surface (need two subvolumes separated by a surface)")
    if surface_name is None:
        if len(surface_objects) > 1:
            raise ValueError("geometry has multiple surfaces; specify surface_name in set_moving_boundary_front(...)")
        return surface_objects[0]
    # Match the requested surface class by the subvolumes it separates.
    geometry = spec.find(_q("Geometry"))
    refs: set[str] = set()
    if geometry is not None:
        for surface_class in geometry.iter(_q("SurfaceClass")):
            if surface_class.get("Name") == surface_name:
                refs = {surface_class.get("SubVolume1Ref", ""), surface_class.get("SubVolume2Ref", "")}
    for obj in surface_objects:
        if {obj.get("subVolumeInside", ""), obj.get("subVolumeOutside", "")} == refs:
            return obj
    raise ValueError(f"surface '{surface_name}' not found among regenerated spatial objects")


def _species_order(setup_file: Path) -> list[str]:
    """Volume species in the order the solver reports concentrations."""
    root = etree.fromstring(setup_file.read_bytes())
    return [
        name
        for species in root.iter("species")
        if species.get("type") == "volume" and (name := species.get("name")) is not None
    ]


def _output_times(sim: Simulation) -> list[float]:
    step = sim.output_time_step
    if step <= 0:
        return [0.0, sim.duration]
    count = round(sim.duration / step)
    times = [min(i * step, sim.duration) for i in range(count + 1)]
    if times[-1] < sim.duration:
        times.append(sim.duration)
    return times
