# coding: utf-8

"""
VCell API

VCell API

The version of the OpenAPI document: 1.0.1
Contact: vcell_support@uchc.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from pyvcell._internal.api.vcell_client.models.spatial_selection_membrane import SpatialSelectionMembrane


class TestSpatialSelectionMembrane(unittest.TestCase):
    """SpatialSelectionMembrane unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpatialSelectionMembrane:
        """Test SpatialSelectionMembrane
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SpatialSelectionMembrane`
        """
        model = SpatialSelectionMembrane()
        if include_optional:
            return SpatialSelectionMembrane(
                type = 'Membrane',
                field_sampled_data_indexes = [
                    56
                    ],
                selection_source = pyvcell._internal.api.vcell_client.models.sampled_curve.SampledCurve(
                    type = 'SampledCurve',
                    default_num_samples = 56,
                    max_control_points = 56,
                    min_control_points = 56,
                    segment_count = 56,
                    spatial_length = 1.337, )
            )
        else:
            return SpatialSelectionMembrane(
                type = 'Membrane',
        )
        """

    def testSpatialSelectionMembrane(self):
        """Test SpatialSelectionMembrane"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
