"""
VCell API

VCell API

The version of the OpenAPI document: 1.0.1
Contact: vcell_support@uchc.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest


class TestVariableDomain(unittest.TestCase):
    """VariableDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariableDomain(self):
        """Test VariableDomain"""
        # inst = VariableDomain()


if __name__ == "__main__":
    unittest.main()
